/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Leave_Apply.java
 *
 * Created on Apr 21, 2014, 2:38:16 AM
 */
package erp.hr.system;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author asimali
 */
public class Leave_Apply extends javax.swing.JDialog {

    /** Creates new form Leave_Apply */
    Leave_Application parent;
    ERPHRSYSTEM obj=new ERPHRSYSTEM();
    public Leave_Apply(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void initialize()
    {
        getContentPane().setBackground(Color.LIGHT_GRAY);
    }
    public void parent_initialization(Leave_Application pr)
    {
        this.parent=pr;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        day1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        month1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        year1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        day2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        month2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        year2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apply for Leave");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(-16777216,true), 5, true));

        jLabel2.setText("Start Date");

        day1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel3.setText("/");

        month1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel5.setText("/");

        year1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel4.setText("/");

        day2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel6.setText("End Date");

        month2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jLabel7.setText("/");

        year2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Leave_Apply.this.focusLost(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submit(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel4)
                                    .addGap(2, 2, 2)
                                    .addComponent(month2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel7)
                                    .addGap(2, 2, 2)
                                    .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel3)
                                    .addGap(2, 2, 2)
                                    .addComponent(month1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addComponent(jLabel5)
                                    .addGap(2, 2, 2)
                                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(month1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(month2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void focusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusGained
// TODO add your handling code here:
    evt.getComponent().setBackground(Color.YELLOW);
}//GEN-LAST:event_focusGained

private void focusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusLost
// TODO add your handling code here:
    evt.getComponent().setBackground(Color.WHITE);
}//GEN-LAST:event_focusLost

private void cancel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel
// TODO add your handling code here:
    dispose();
    parent.setVisible(true);
}//GEN-LAST:event_cancel

private void submit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submit
// TODO add your handling code here:
    int e=0, m=0;
    String query;
    try{
        query="select employee_id, reporting_authority from Employee where username='"+obj.username+"';";
        obj.rs=obj.stm.executeQuery(query);
        if(obj.rs.next())
        {
            e=obj.rs.getInt(1);
            m=obj.rs.getInt(2);
        }
        String sd=year1.getText()+"-"+month1.getText()+"-"+day1.getText();
        String ed=year2.getText()+"-"+month2.getText()+"-"+day2.getText();
        query="insert into leave_form(employee_id, start, end, approve_id, status) values("+e+",'"+sd+"','"+ed+"',"+m+",'waiting')";
        obj.stm.execute(query);
        JOptionPane.showMessageDialog(null, "Leave added successfully!!");
        }
        catch(Exception ex){
            System.out.println("Error: "+ex);
            JOptionPane.showMessageDialog(null, "There was some error in executing adding the leave!!");
        }
}//GEN-LAST:event_submit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leave_Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leave_Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leave_Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leave_Apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Leave_Apply dialog = new Leave_Apply(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField day1;
    private javax.swing.JTextField day2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField month1;
    private javax.swing.JTextField month2;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
}
